Create LICENSE
globus-gladier/gladier pull request #178
Opened 2022-07-19 21:18 UTC by blaiszik

2022-07-19 21:55 UTC, NickolausDS requested changes
All other Globus Tooling I'm aware of uses the Apache 2 license, can we use that instead?

2022-09-26 15:57 UTC, ravescovi approved these changes

2022-09-26 16:04 UTC, ravescovi requested changes

2022-09-26 16:04 UTC, ravescovi commented on gladier/client.py
> -        cfg[self.section][fxid_name] = self.funcx_client.register_function(function,
Should this change be on this PR?

2022-09-27 16:56 UTC, NickolausDS commented
Closing in favor of #196

2022-09-27 16:56 UTC, closed without merging